site: Kevin Noonan
url: https://KNoonan95.github.io
title: Kevin Noonan
author:
  name:  Kevin Noonan
  picture: /images/MeOnTowntinna.jpg
  email: knoonan1995@gmail.com
description: Portfolio website
welcome: Hi, My name is Kevin , welcome to my site

accent_image:
  background: 'light-blue'
  overlay:    false    

font: "sans-serif"
font_heading: "sans-serif"
hydejack:
  no_google_fonts: true

permalink: pretty

paginate:      5
paginate_path: 'index.html'


optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-avatar

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug

theme: jekyll-theme-hydejack

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

compress_html:
comments:            ['<!-- ', ' -->']
clippings:           all
endings:             all


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

